In [1]:
import pandas as pd
import numpy as np

In [17]:
neg = pd.read_csv('all-comments.csv')
pos = pd.read_csv('comments.csv')
neg["y"] = 0
neg.describe()

,Unnamed: 0,Score,PostScore,Number_Of_Comments,Publish_Date,y
count,52816.000000,52816.000000,52816.000000,52816.000000,5.281600e+04,52816.0
mean,26407.500000,31.450432,7568.993354,473.607505,1.657280e+09,0.0
std,15246.810246,249.324450,11169.990243,630.507605,1.196804e+04,0.0
min,0.000000,-153.000000,305.000000,1.000000,1.657237e+09,0.0
25%,13203.750000,1.000000,1528.000000,115.000000,1.657273e+09,0.0
50%,26407.500000,1.000000,3403.000000,262.000000,1.657282e+09,0.0
75%,39611.250000,4.000000,8087.000000,605.000000,1.657289e+09,0.0
max,52815.000000,17580.000000,78192.000000,7854.000000,1.657303e+09,0.0

In [19]:
neg=neg.sample(pos.shape[0])
df = pd.concat([neg, pos], ignore_index=True)
df.to_csv('compassion.csv', index=False)
df.describe()

,Unnamed: 0,Score,PostScore,Number_Of_Comments,Publish_Date,y
count,11894.000000,11894.00000,11894.000000,11894.000000,1.189400e+04,11894.000000
mean,14709.761813,17.21431,4181.227342,279.644106,1.656912e+09,0.500000
std,15952.616013,106.66113,8250.183492,469.763232,4.765151e+05,0.500021
min,0.000000,-105.00000,0.000000,1.000000,1.655828e+09,0.000000
25%,2683.250000,1.00000,298.000000,37.000000,1.656548e+09,0.000000
50%,5341.500000,2.00000,1367.000000,117.000000,1.657241e+09,0.500000
75%,26589.000000,4.00000,3796.000000,341.000000,1.657282e+09,1.000000
max,52810.000000,4762.00000,78192.000000,7854.000000,1.657303e+09,1.000000